# Generated by Django 3.0.8 on 2020-07-30 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Заголовок')),
                ('telephone', models.CharField(max_length=20, verbose_name='Телефон сварщика')),
            ],
        ),
        migrations.CreateModel(
            name='Forging',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Заголовок')),
                ('content', models.TextField(verbose_name='Описание')),
                ('is_published', models.BooleanField(blank=True, default=False, verbose_name='Опубликовать')),
                ('photo', models.ImageField(upload_to='media/', verbose_name='Фото')),
            ],
        ),
    ]
