# Generated by Django 3.0.8 on 2020-07-30 14:31

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('forging', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='forging',
            options={'verbose_name': 'Ковку', 'verbose_name_plural': 'Кованные изделия'},
        ),
        migrations.AddField(
            model_name='forging',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='forging.Category', verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='forging',
            name='published_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата публикации'),
            preserve_default=False,
        ),
    ]
